/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Floyd' at '15/10/19 11:55 PM' with Gradle 3.0
 *
 * @author Floyd, @date 15/10/19 11:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
