/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Floyd' at '17/10/19 6:17 PM' with Gradle 3.0
 *
 * @author Floyd, @date 17/10/19 6:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
