/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Floyd' at '14/10/19 11:55 AM' with Gradle 3.0
 *
 * @author Floyd, @date 14/10/19 11:55 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
