/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Floyd' at '22/10/19 11:53 AM' with Gradle 3.0
 *
 * @author Floyd, @date 22/10/19 11:53 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
