/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Floyd' at '18/10/19 12:37 AM' with Gradle 3.0
 *
 * @author Floyd, @date 18/10/19 12:37 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
